USD: us
EUR: eu
GBP: gb
CHF: ch
JPY: jp
CAD: ca
AUD: au
NOK: no
SEK: se
DKK: dk
CZK: cz
HUF: hu
PLN: pl
CNY: cn
RUB: ru
UAH: ua
ISK: is
NZD: nz
SGD: sg
KRW: kr
THB: th
MYR: my
HRK: hr
BGN: bg
RON: ro
TRY: tr
ILS: il
CLP: cl
PHP: ph
MXN: mx
ZAR: za
BRL: br
ARS: ar
